# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 100
  start_block: 0
  contracts:
  - name: PrematchCore
    address:
    - 0x7f3F3f19c4e4015fd9Db2f22e653c766154091EF
    handler: src/EventHandlers.ts
    events:
    - event: OddsChanged(uint256 indexed conditionId, uint256[] newOdds)
  - name: FreeBet
    address:
    - 0xAC2476Db1FD2f3E7D1dA7ccC3fAC7D1bD1c4B5a2
    handler: src/EventHandlers.ts
    events:
    - event: NewBet(uint256 indexed freeBetId, address core, address indexed bettor, uint256 indexed azuroBetId, uint128 amount, uint64 minOdds, uint64 expiresAt)
  # - name: Core
  #   address:
  #   - 0xC95C831c7bDb0650b8cD5F2a542b263872d8ed0e
  #   handler: src/EventHandlers.ts
  #   events:
  #   - event: OddsChanged(uint256 indexed conditionId, uint64[2] newOdds)
rollback_on_reorg: false
